<?php $this->headTitle()->append('Delete Assignment'); ?>

Delete assignment:<br/>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<p class="warning">Are you sure that you want to delete assignment: <?php echo $this->escape($this->assignment->title); ?>?</p>
	<div class="buttons">
		<input type="hidden" name="id" value="<?php echo $this->escape($this->assignment->id); ?>" />
		<input type="submit" name="delete" id="leftButton" value="Yes" />&nbsp;<input type="submit" id="rightButton" name="delete" value="No" />
	</div>
</form>