<?php $this->headTitle()->append('Delete User'); ?>

Delete user:<br/>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<p class="warning">Are you sure that you want to delete user: <?php echo $this->escape($this->user->firstname); ?> <?php echo $this->escape($this->user->lastname); ?>?</p>
	<div class="buttons">
		<input type="hidden" name="id" value="<?php echo $this->escape($this->user->id); ?>" />
		<input type="submit" name="delete" id="leftButton" value="Yes" />&nbsp;<input type="submit" id="rightButton" name="delete" value="No" />
	</div>
</form>