<?php $this->headTitle()->append('Users'); ?>

<p><a href="<?php echo $this->url(
    array(
        'controller' => 'user',
        'action'     => 'add'
    ),
    'default',
    true) ?>">Add New User</a></p>
 
<div id="form">
Existing Users: <br />
<table class="tblList">
	<tr>
		<th width="20%">Username</th>
		<th width="40%">First Name</th>
		<th width="40%">Last Name</th>
		<th width="5%"></th>
	</tr>
    <?php foreach ($this->entries as $entry): ?>
    <tr>
    	<td width="15%"><?php echo $this->escape($entry->username) ?></td>
    	<td width="40%"><?php echo $this->escape($entry->firstname) ?></td>
    	<td width="40%"><?php echo $this->escape($entry->lastname) ?></td>
    	<td width="5%"><a href="<?php echo $this->url(
		    array(
		        'controller' => 'user',
		        'action'     => 'edit',
		    	'id'		 => $entry->id
		    ),
		    'default',
		    true) ?>">edit</a>&nbsp;|&nbsp;<a href="<?php echo $this->url(
		    array(
		        'controller' => 'user',
		        'action'     => 'delete',
		    	'id'		 => $entry->id
		    ),
		    'default',
		    true) ?>">delete</a></td>
    </tr>
    <?php endforeach ?>
</table>
</div>